// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsLzhQT4YVirDqAauPDdW13Hv4EtULpUU',
    appId: '1:345121227378:web:383c59b75ab947ab0ff8eb',
    messagingSenderId: '345121227378',
    projectId: 'smart-citizen-app-a7344',
    authDomain: 'smart-citizen-app-a7344.firebaseapp.com',
    storageBucket: 'smart-citizen-app-a7344.firebasestorage.app',
    measurementId: 'G-SY5CW6X0H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHE-Qh96JB1Aa8UO_x-jfjydKf9maTVFI',
    appId: '1:345121227378:android:23400140ab9d7bcb0ff8eb',
    messagingSenderId: '345121227378',
    projectId: 'smart-citizen-app-a7344',
    storageBucket: 'smart-citizen-app-a7344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCExJHICkfEtLHNK5FmLD9_wQ-0BBSqg5o',
    appId: '1:345121227378:ios:a3e239751b9e4ff50ff8eb',
    messagingSenderId: '345121227378',
    projectId: 'smart-citizen-app-a7344',
    storageBucket: 'smart-citizen-app-a7344.firebasestorage.app',
    iosBundleId: 'com.example.citizenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCExJHICkfEtLHNK5FmLD9_wQ-0BBSqg5o',
    appId: '1:345121227378:ios:a3e239751b9e4ff50ff8eb',
    messagingSenderId: '345121227378',
    projectId: 'smart-citizen-app-a7344',
    storageBucket: 'smart-citizen-app-a7344.firebasestorage.app',
    iosBundleId: 'com.example.citizenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsLzhQT4YVirDqAauPDdW13Hv4EtULpUU',
    appId: '1:345121227378:web:a12fdaefdefc93530ff8eb',
    messagingSenderId: '345121227378',
    projectId: 'smart-citizen-app-a7344',
    authDomain: 'smart-citizen-app-a7344.firebaseapp.com',
    storageBucket: 'smart-citizen-app-a7344.firebasestorage.app',
    measurementId: 'G-6K75ERR831',
  );
}
